//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitAreaReinforcement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitAreaReinforcement.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get rebar type .
        /// </summary>
        public static string ErrorFailedToGetRebarType {
            get {
                return ResourceManager.GetString("ErrorFailedToGetRebarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter Mtrl.Code in material .
        /// </summary>
        public static string ErrorNoMaterialCodeParameter {
            get {
                return ResourceManager.GetString("ErrorNoMaterialCodeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter Rbr.ProfileCode in element .
        /// </summary>
        public static string ErrorNoRebarCodeParam {
            get {
                return ResourceManager.GetString("ErrorNoRebarCodeParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter Dim.SlabHeight in element.
        /// </summary>
        public static string ErrorNoSlabHeightParam {
            get {
                return ResourceManager.GetString("ErrorNoSlabHeightParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable floor for reinforcement.
        /// </summary>
        public static string MessageNoCorrectFloors {
            get {
                return ResourceManager.GetString("MessageNoCorrectFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-structural floor is found, failed to create reinforcement.
        /// </summary>
        public static string MessageNoStructuralFloors {
            get {
                return ResourceManager.GetString("MessageNoStructuralFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-structural walls is found, failed to create reinforcement.
        /// </summary>
        public static string MessageNoStructuralWalls {
            get {
                return ResourceManager.GetString("MessageNoStructuralWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select area reinforcements.
        /// </summary>
        public static string MessageSelectAreaRebar {
            get {
                return ResourceManager.GetString("MessageSelectAreaRebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select floors to reinforcement.
        /// </summary>
        public static string MessageSelectFloors {
            get {
                return ResourceManager.GetString("MessageSelectFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select wall to reiforcement.
        /// </summary>
        public static string MessageSelectWalls {
            get {
                return ResourceManager.GetString("MessageSelectWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class .
        /// </summary>
        public static string RebarClass {
            get {
                return ResourceManager.GetString("RebarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottom X background.
        /// </summary>
        public static string TextBottomXrebar {
            get {
                return ResourceManager.GetString("TextBottomXrebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottom Y background.
        /// </summary>
        public static string TextBottomYrebar {
            get {
                return ResourceManager.GetString("TextBottomYrebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main horizontal.
        /// </summary>
        public static string TextHorizontalRebarPartition {
            get {
                return ResourceManager.GetString("TextHorizontalRebarPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top X background.
        /// </summary>
        public static string TextTopXrebar {
            get {
                return ResourceManager.GetString("TextTopXrebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top Y background.
        /// </summary>
        public static string TextTopYrebar {
            get {
                return ResourceManager.GetString("TextTopYrebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main vertical.
        /// </summary>
        public static string TextVerticalRebarPartition {
            get {
                return ResourceManager.GetString("TextVerticalRebarPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors reinforcement.
        /// </summary>
        public static string TransactionFloorReinforcement {
            get {
                return ResourceManager.GetString("TransactionFloorReinforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls reinforcement.
        /// </summary>
        public static string TransactionWallReinforcement {
            get {
                return ResourceManager.GetString("TransactionWallReinforcement", resourceCulture);
            }
        }
    }
}
